# ----------------------Custom ScoreBoard---------------------- #
# Use %player% to get the player (YOU) #
# Use %gamemode% to get *YOUR CURRENT* gamemode #
# Use %world% to get the world where *YOU CURRENT* are #
# Config version : Config.version = 1.0.0 #
# Config created by; SmikkelBeertjes (Kane), JoranDev (Joran) #
# Plugin created by; SmikkelBeertjes (Kane) #
# Date created config/plugin 21-10-2018, editted this at 16-07-2019#
# Having fun with this scoreboard plugin #
# Any problems? Join than our discord server; https://discord.gg/pM95X7u #
# ------------------------------------------------------------- #

ScoreBoard:
  Name: '&f- &2&lKikkerCraft &f-'
  Player: '&7%player%'
  Gamemode: '&7%gamemode%'
  World: '&7%world%'
  Ip: '&aplay.kikkercraft.nl'
  Rank: '%Rank%'
  Website: '&7www.kikkercraft.nl'
