name: CustomStatsScoreBoard
version: 1.1
description: A cool scoreboard plugin for you!
author: SmikkelBeertjes
authors: [SBDeveloper]

main: me.scoreboard.Main
depend: [Vault]

commands:
   customboardz:
      description: The main command of the plugin!
      aliases: [cz, customb, cboardz, cboard]