name: CustomStatsScoreBoard
version: 1.1
description: A cool scoreboard plugin for you!
author: SmikkelBeertjes
authors: [SBDeveloper]

main: me.scoreboard.Main
depend: [Vault]

commands:
   reloadscoreboard:
      description: Reload all the config files
      aliases: [reloadsc, rlscoreboard, rlsc]
   helpscoreboard:
      description: Help command
      aliases: [helpsc, hscoreboard, csshelp]
   staff:
      description: Staff command(s)
      aliases: [staff, staffscoreboard, staffsc, cssstaf]
      
