name: CustomStatsScoreBoard
author: SBDDeveloper, SmikkelBeertjes
main: me.scoreboard.Main
version: 1.0
depend: [Vault]
commands:
   reloadscoreboard:
      description: Reload all the config files
      aliases: [reloadsc, rlscoreboard, rlsc]
   helpscoreboard:
      description: Help command
      aliases: [helpsc, hscoreboard, csshelp]
   staff:
      description: Staff command(s)
      aliases: [staff, staffscoreboard, staffsc, cssstaf]
      
